name: Run python tests
on:
    push:
        branches:
            - main
            - proto_main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - name: Install python3
              uses: actions/setup-python@v4
              with:
                  python-version: 3.12
            - name: Install dependancies
              run: |
                  python -m pip install --upgrade pip
                  pip install setuptools==69.0.3
                  pip install -r requirements_fixed.txt
                  pip install pytest pytest-mock coverage
            - name: Get submodules
              run: git submodule update --init --recursive
            - name: Run tests with pytest
              run: |
                  coverage run -m pytest test/test*py
                  coverage xml -i
                  coverage report -i
